#!/usr/bin/env python3

import sys
import os

def usage():
    print("wrong args")
    print("ndfs init <target>")

if __name__ == "__main__":
    target = sys.argv[1]
    print("will init", target)
    try:
        os.makedirs(target+"/.ndfs")
    except Exception as e:
        print(e)
        exit(1)
    print(target, "has been inited")

