#!/usr/bin/env python3

import sys
import os
import time
import logging

FORMAT = "%(asctime)s: %(message)s"
logging.basicConfig(format=FORMAT)
formatter = logging.Formatter(fmt=FORMAT)
logger = logging.getLogger()
logger.setLevel(logging.NOTSET)

def usage():
    print("wrong args")
    print("ndfs init <target>")

if __name__ == "__main__":
    target = sys.argv[1]
    print("will init", target)
    try:
        os.makedirs(target+"/.ndfs")
        logfile = logging.FileHandler(target+"/.ndfs/ndfs.log")
        logfile.setFormatter(formatter)
        logger.addHandler(logfile)
        logger.info("init %s", target)
        #log = "{}: init {}\n".format(time.asctime(), target)
        #open(target+"/.ndfs/ndfs.log","a").write(log)
    except Exception as e:
        print(e)
        exit(1)
    print(target, "has been inited")
